Rebase on jessie's systemd-215-12

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -3,135 +3,210 @@
 #export DH_VERBOSE=1
 #export DEB_BUILD_OPTIONS="nostrip"
 
-FLAVORS = deb udeb
-
-VERSION = $(shell dpkg-parsechangelog | sed -n -e '/^Version:/s/.*: //p')
-
 DEB_HOST_MULTIARCH ?= $(shell dpkg-architecture -qDEB_HOST_MULTIARCH)
-DEB_BUILD_GNU_TYPE ?= $(shell dpkg-architecture -qDEB_BUILD_GNU_TYPE)
+
+ifneq (,$(findstring stage1,$(DEB_BUILD_PROFILES)))
+BOOTSTRAP_DH_FLAGS := -Ngir1.2-gudev-1.0 -Nlibgudev-1.0-0 -Nlibgudev-1.0-dev
+endif
 
 CONFFLAGS = \
-	--disable-silent-rules \
-	--build=$(DEB_BUILD_GNU_TYPE) \
-	--prefix=/usr \
-	--sysconfdir=/etc \
-	--localstatedir=/var \
-	--libdir=\$${prefix}/lib/$(DEB_HOST_MULTIARCH) \
-	--libexecdir=\$${prefix}/lib/$(DEB_HOST_MULTIARCH) \
 	--with-rootprefix= \
 	--with-rootlibdir=/lib/$(DEB_HOST_MULTIARCH) \
-	--with-firmware-path=/lib/firmware	\
+	--with-zshcompletiondir=/usr/share/zsh/vendor-completions \
 	--with-sysvinit-path=/etc/init.d \
 	--with-sysvrcnd-path=/etc \
-	--enable-libcryptsetup \
-	--enable-tcpwrap \
+	--with-firmware-path=/lib/firmware \
+	--with-debug-shell=/bin/bash \
+	--with-telinit=/lib/sysvinit/telinit \
 	--disable-coredump \
 	--disable-efi \
 	--disable-myhostname \
-	--disable-keymap \
-	--disable-vconsole
+	--disable-vconsole \
+	--disable-microhttpd \
+	--disable-sysusers \
+	--disable-silent-rules \
+	--with-ntp-servers="0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org"  \
+	--with-system-uid-max=999 \
+	--with-system-gid-max=999
+
+ifeq (,$(findstring stage1,$(DEB_BUILD_PROFILES)))
+CONFFLAGS += --enable-libcryptsetup
+endif
 
 CONFFLAGS_deb = \
 	--enable-selinux \
 	--enable-introspection \
-	--enable-gtk-doc
+	--enable-gtk-doc \
+	--enable-compat-libs \
+	PYTHON=python3 \
+	$(NULL)
 
 CONFFLAGS_udeb = \
+	--disable-libcryptsetup \
+	--disable-pam \
+	--disable-audit \
 	--disable-selinux \
+	--disable-smack \
+	--disable-ima \
 	--disable-introspection \
 	--disable-gtk-doc \
 	--disable-binfmt \
 	--disable-readahead \
 	--disable-bootchart \
 	--disable-quotacheck \
+	--disable-tmpfiles \
 	--disable-randomseed \
+	--disable-backlight \
 	--disable-logind \
+	--disable-machined \
 	--disable-hostnamed \
 	--disable-timedated \
+	--disable-networkd \
+	--disable-timesyncd \
 	--disable-localed \
+	--disable-resolved \
 	--disable-polkit \
 	--disable-acl \
-	--disable-xattr \
+	--disable-gcrypt \
 	--disable-gudev \
+	--disable-rfkill \
+	--disable-multi-seat-x \
 	--disable-manpages \
 	--without-python
 
-# Ubuntu: systemd{,-sysv} not yet approved for universe
-ifeq ($(shell dpkg-vendor --derives-from Ubuntu && echo ubuntu),ubuntu)
-BINARY_BLACKLIST = -Nsystemd -Nsystemd-sysv
-endif
+override_dh_auto_configure:
+	dh_auto_configure --builddirectory=build-deb \
+		-- $(CONFFLAGS) $(CONFFLAGS_deb)
+	dh_auto_configure --builddirectory=build-udeb \
+		-- $(CONFFLAGS) $(CONFFLAGS_udeb)
 
-override_dh_auto_configure: $(FLAVORS:%=debian/stamps/configure-%)
-debian/stamps/configure-%:
-	mkdir -p debian/build/$*
-	mkdir -p debian/stamps/
-	# workaround for gtk-doc sucking at oot builds
-	tar cpf - . --exclude=debian | tar xpf - -C debian/build/$*
-	cd debian/build/$* && ./configure $(CONFFLAGS) $(CONFFLAGS_$*)
-	touch $@
+override_dh_auto_build:
+	dh_auto_build --builddirectory=build-deb
+	dh_auto_build --builddirectory=build-udeb
 
-override_dh_auto_build: $(FLAVORS:%=debian/stamps/build-%)
-debian/stamps/build-%:
-	# remove pre-generated man pages so they are rebuilt
-	rm -f debian/build/$*/man/*.[13578]
-	make -C debian/build/$*
-
-override_dh_auto_install: $(FLAVORS:%=debian/stamps/install-%)
-debian/stamps/install-%:
-	make -C debian/build/$* install DESTDIR=$(CURDIR)/debian/install/$*
+override_dh_auto_install:
+	dh_auto_install --builddirectory=build-deb \
+		--destdir=debian/install/deb
+	dh_auto_install --builddirectory=build-udeb \
+		--destdir=debian/install/udeb
 
 override_dh_auto_clean:
-	dh_auto_clean
-	rm -rf debian/build/
+	dh_auto_clean --builddirectory=build-deb
+	dh_auto_clean --builddirectory=build-udeb
 	rm -rf debian/install/
-	rm -rf debian/stamps/
+	# remove pre-generated man pages so they are rebuilt
+	rm -f man/*.[13578]
+	# remove pre-generated rules and unit files so they are rebuilt
+	rm -f rules/99-systemd.rules \
+		units/emergency.service \
+		units/systemd-udevd.service \
+		units/systemd-udev-settle.service \
+		units/systemd-udev-trigger.service
+	# remove Python byte code files
+	rm -f *.pyc
 
 override_dh_install:
+	# remove unnecessary / unused files
 	rm -f debian/install/*/usr/share/doc/systemd/LICENSE.*
 	rm -f debian/install/*/var/log/README
 	rm -f debian/install/*/etc/init.d/README
+	rm -f debian/install/*/usr/share/man/man8/kernel-install.8
+	rm -f debian/install/*/usr/bin/kernel-install
+	rm -f debian/install/*/usr/share/zsh/vendor-completions/_kernel-install
+	rm -f debian/install/*/usr/share/bash-completion/completions/kernel-install
+	rm -rf debian/install/*/usr/lib/kernel/install.d
+	rm -rf debian/install/*/etc/rpm/
+	rm -rf debian/install/*/usr/lib/rpm/
+	rm -rf debian/install/*/etc/kernel/
+	rm -f debian/install/*/usr/lib/sysctl.d/50-default.conf
 	find debian/install/ -name '*.la' -delete
-ifeq (udeb ,$(filter udeb, $(FLAVORS)))
+	# remove files related to factory-reset feature
+	find debian/install/ \( -name 'systemd-update-done*' -o \
+		-name systemd-journal-catalog-update.service -o \
+		-name systemd-udev-hwdb-update.service -o \
+		-name ldconfig.service -o \
+		-name etc.conf \) -delete
+	# remove .so for deprecated compatibility libraries
+	rm -f debian/install/*/usr/lib/*/libsystemd-daemon.so
+	rm -f debian/install/*/usr/lib/*/libsystemd-login.so
+	rm -f debian/install/*/usr/lib/*/libsystemd-id128.so
+	rm -f debian/install/*/usr/lib/*/libsystemd-journal.so
+	# remove symlinks enabling default-on services
+	rm -rf debian/install/*/etc/systemd/system/*.target.wants/
 	dh_install -pudev-udeb -plibudev1-udeb --sourcedir=debian/install/udeb
+	dh_install $(BOOTSTRAP_DH_FLAGS) -Nudev-udeb -Nlibudev1-udeb --sourcedir=debian/install/deb --fail-missing
+	# install some files manually, --sourcedir makes that necessary
 	# udev-udeb
 	install -D --mode=755 debian/extra/udev.startup \
 		debian/udev-udeb/lib/debian-installer/start-udev
 	install -D --mode=755 debian/extra/udev.base-installer \
 		debian/udev-udeb/usr/lib/base-installer.d/05udev
-	# drop rules which we don't need in the installer
-	rm debian/udev-udeb/lib/udev/rules.d/60-persistent-v4l.rules
-	rm debian/udev-udeb/lib/udev/rules.d/61-accelerometer.rules
-endif
-	dh_install -Nudev-udeb -Nlibudev1-udeb --sourcedir=debian/install/deb -O--parallel -Xetc/rpm/ --list-missing
-	# install some files manually, --sourcedir makes that necessary
-	# systemd
-	cp -a debian/pam-configs debian/libpam-systemd/usr/share/
-	install -D --mode=644 debian/init-functions.d/40-systemd \
-		debian/systemd/lib/lsb/init-functions.d/40-systemd
-	install --mode=644 debian/tmpfiles.d/debian.conf \
-		debian/systemd/usr/lib/tmpfiles.d/
-	install --mode=644 debian/debian-fixup.service debian/ifup@.service \
-		debian/units/run-lock.mount debian/units/run-user.mount \
-		debian/debian-enable-units.service \
-		debian/systemd/lib/systemd/system/
-	install --mode=644 debian/unit.blacklist \
-		debian/systemd/usr/share/systemd/
-	install --mode=755 debian/debian-fixup debian/debian-enable-units \
-		debian/systemd/lib/systemd/
-	# initramfs-tools support
+	mkdir -p debian/udev-udeb/lib/udev/rules.d/
+	install -D --mode=644 \
+		debian/extra/rules/73-idrac.rules \
+		debian/extra/rules/75-persistent-net-generator.rules \
+		debian/udev-udeb/lib/udev/rules.d/
+	mkdir -p debian/udev-udeb/lib/udev
+	install -D --mode=644 \
+		debian/extra/hotplug.functions \
+		debian/extra/rule_generator.functions \
+		debian/udev-udeb/lib/udev/
+	install -D --mode=755 \
+		debian/extra/write_net_rules \
+		debian/udev-udeb/lib/udev/
+	# udev: initramfs-tools support
 	install -D --mode=755 debian/extra/initramfs.hook \
 		debian/udev/usr/share/initramfs-tools/hooks/udev
 	install -D --mode=755 debian/extra/initramfs.top \
 		debian/udev/usr/share/initramfs-tools/scripts/init-top/udev
 	install -D --mode=755 debian/extra/initramfs.bottom \
 		debian/udev/usr/share/initramfs-tools/scripts/init-bottom/udev
-	# documentation
-	install -m 644 -o root -g root debian/extra/README-etc-rules.d \
-		debian/udev/etc/udev/rules.d/README
-	install -m 644 -o root -g root debian/extra/README-lib-rules.d \
-		debian/udev/lib/udev/rules.d/README
-
-	# TODO: use a script to find duplicates and remove them automatically
+	# udev: debian specific rules and helpers
+	install -D --mode=644 debian/extra/rules/* \
+		debian/udev/lib/udev/rules.d/
+	install -D --mode=644 debian/extra/fbdev-blacklist.conf \
+		debian/udev/etc/modprobe.d/fbdev-blacklist.conf
+	install -D --mode=644 \
+		debian/extra/hotplug.functions \
+		debian/extra/rule_generator.functions \
+		debian/udev/lib/udev/
+	install -D --mode=755 \
+		debian/extra/dsl-modem.agent \
+		debian/extra/logger.agent \
+		debian/extra/net.agent \
+		debian/extra/udev-finish \
+		debian/extra/write_net_rules \
+		debian/udev/lib/udev/
+	# systemd
+	cp -a debian/pam-configs debian/libpam-systemd/usr/share/
+	install -D --mode=644 debian/init-functions.d/40-systemd \
+		debian/systemd/lib/lsb/init-functions.d/40-systemd
+	install --mode=644 debian/tmpfiles.d/debian.conf \
+		debian/systemd/usr/lib/tmpfiles.d/
+	install --mode=644 debian/debian-fixup.service debian/ifup@.service debian/extra/getty-static.service \
+		debian/systemd/lib/systemd/system/
+	install -D --mode=644 debian/extra/network-pre.conf \
+		debian/systemd/lib/systemd/system/networking.service.d/network-pre.conf
+	install --mode=644 debian/extra/udev-finish.service \
+		debian/udev/lib/systemd/system/
+	ln -s ../udev-finish.service debian/udev/lib/systemd/system/sysinit.target.wants/
+	install --mode=755 debian/debian-fixup \
+		debian/systemd/lib/systemd/
+	# Make sure the runlevel services are known by systemd so their targets
+	# get launches. See https://bugzilla.redhat.com/show_bug.cgi?id=1002806
+	for t in poweroff rescue multi-user graphical reboot; do \
+		mkdir -p debian/systemd/lib/systemd/system/$${t}.target.wants;\
+		ln -s ../systemd-update-utmp-runlevel.service \
+			debian/systemd/lib/systemd/system/$${t}.target.wants ;\
+	done
+	# man files for example code in /usr/share/doc
+	mkdir -p debian/systemd/usr/share/man/man3/
+	mv debian/libsystemd-dev/usr/share/man/man3/sd-readahead.3 \
+		debian/libsystemd-dev/usr/share/man/man3/sd_readahead.3 \
+		debian/systemd/usr/share/man/man3/
+	install --mode=755 debian/systemd-logind-launch \
+		debian/systemd/lib/systemd/
+	# remove duplicates
 	# files shipped by systemd-sysv / sysvinit
 	rm debian/systemd/usr/share/man/man1/init.1
 	rm debian/systemd/usr/share/man/man8/halt.8
@@ -143,77 +218,75 @@ endif
 	# files shipped by libpam-systemd
 	rm debian/systemd/usr/share/man/man8/pam_systemd.8
 	# files shipped by udev
+	rm -r debian/systemd/etc/udev/
 	rm debian/systemd/lib/systemd/system/systemd-udev*
 	rm debian/systemd/lib/systemd/system/*.target.wants/systemd-udev*
 	rm debian/systemd/lib/systemd/systemd-udevd
 	rm debian/systemd/usr/share/man/man7/udev.7
 	rm debian/systemd/usr/share/man/man8/*udev*.8
+	# files shipped by udev / bash-completion
+	rm debian/systemd/usr/share/bash-completion/completions/udevadm
 	# files systemd by cryptsetup
+ifeq (,$(findstring stage1,$(DEB_BUILD_PROFILES)))
 	rm debian/systemd/usr/share/man/man5/crypttab.5
-	# files shipped by systemd-services
-	rm debian/systemd/etc/systemd/logind.conf
-	rm debian/systemd/lib/systemd/systemd-logind
-	rm debian/systemd/lib/systemd/systemd-hostnamed
-	rm debian/systemd/lib/systemd/systemd-localed
-	rm debian/systemd/lib/systemd/systemd-timedated
-	rm debian/systemd/usr/share/man/man5/logind*
-	rm debian/systemd/usr/share/man/man8/systemd-logind*
-	rm debian/systemd/usr/share/man/man8/systemd-hostnamed*
-	rm debian/systemd/usr/share/man/man8/systemd-localed*
-	rm debian/systemd/usr/share/man/man8/systemd-timedated*
+endif
+	# files shipped by systemd
 	rm debian/udev/lib/udev/rules.d/70-uaccess.rules
 	rm debian/udev/lib/udev/rules.d/73-seat-late.rules
 	rm debian/udev/lib/udev/rules.d/71-seat.rules
-	# files shipped by systemd
 	rm debian/udev/lib/udev/rules.d/99-systemd.rules
 
-	# we continue to use the old net iface naming schema for the time being
-	rm debian/udev/lib/udev/rules.d/80-net-name-slot.rules
-	rm debian/udev-udeb/lib/udev/rules.d/80-net-name-slot.rules
+# use symlinked doc directories as the old udev package did
+override_dh_installdocs:
+	dh_installdocs -pudev -plibudev-dev --link-doc=libudev1
+	# we have to manually install udev's README for the above
+	install -D --mode 644 debian/udev.README.Debian debian/libudev1/usr/share/doc/libudev1/README.Debian
+	dh_installdocs -pgir1.2-gudev-1.0 -plibgudev-1.0-dev --link-doc=libgudev-1.0-0
+	dh_installdocs --remaining-packages
+
+override_dh_installinit:
+	dh_installinit --no-start
+	dh_installinit --name=udev-finish --no-start
+	dh_installinit --name=udevtrigger --no-start
+	dh_installinit --name=udevmonitor --no-start
+	dh_installinit --name=udev-fallback-graphics --no-start
+
+# The SysV compat tools (which are symlinks to systemctl) are
+# quasi-essential, so add its dependencies to Pre-Depends
+# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=753589
+override_dh_shlibdeps:
+	dh_shlibdeps -psystemd -- -dPre-Depends -edebian/systemd/bin/systemctl -dDepends
+	dh_shlibdeps --remaining-packages
 
 override_dh_makeshlibs:
 	dh_makeshlibs -plibudev1 --add-udeb=libudev1-udeb
 	dh_makeshlibs --remaining-packages
 
-override_dh_installinit:
-	dh_installinit --upstart-only --no-start
-	dh_installinit --upstart-only --name=udev-finish --no-start
-	dh_installinit --upstart-only --name=udevtrigger --no-start
-	dh_installinit --upstart-only --name=udevmonitor --no-start
-	dh_installinit --upstart-only --name=udev-fallback-graphics --no-start
-	dh_installinit --upstart-only --name systemd-logind --no-start
-
 autoreconf:
-	cp -f /usr/share/gtk-doc/data/gtk-doc.make docs/
+	gtkdocize --copy --docdir docs/
 	intltoolize -f -c
 	autoreconf -f -i
 
 override_dh_autoreconf:
 	dh_autoreconf debian/rules -- autoreconf
 
+override_dh_strip:
+	dh_strip --dbg-package=systemd-dbg
+
 override_dh_auto_test:
+ifeq (, $(findstring nocheck, $(DEB_BUILD_OPTIONS)))
 	# some tests hang under fakeroot, so disable fakeroot
-	echo "01234567890123456789012345678901" > debian/build/machine-id
-	#env -u LD_PRELOAD SYSTEMD_MACHINE_ID_PATH=$(CURDIR)/debian/build/machine-id \
-	#	make -C debian/build/deb check || ( \
-	#	cd debian/build/deb; \
-	#	for f in test-*.log; do echo "==== $$f ===="; cat $$f; done; \
-	#	exit 1; )
-
-%:
-	dh $@ --with autoreconf,gir,python2
-
-override_dh_gencontrol:
-ifeq ($(shell dpkg-vendor --derives-from Ubuntu && echo ubuntu),ubuntu)
-	# Ubuntu has an epoch on gudev
-	dh_gencontrol -plibgudev-1.0-0 -plibgudev-1.0-dev -- "-v1:$(VERSION)"
-	dh_gencontrol $(BINARY_BLACKLIST) --remaining-packages
-else
-	dh_gencontrol $(BINARY_BLACKLIST)
+	echo "01234567890123456789012345678901" > build-deb/machine-id
+	env -u LD_PRELOAD SYSTEMD_MACHINE_ID_PATH=$(CURDIR)/build-deb/machine-id \
+		make -C build-deb check || ( \
+		cd build-deb; \
+		for f in test-*.log; do echo "==== $$f ===="; cat $$f; done; \
+		exit 0; )  # replace with 1 to make failures fatal
 endif
 
-override_dh_strip:
-	dh_strip $(BINARY_BLACKLIST)
-
-override_dh_builddeb:
-	dh_builddeb $(BINARY_BLACKLIST)
+%:
+ifeq (,$(findstring stage1,$(DEB_BUILD_PROFILES)))
+	dh $@ --with autoreconf,gir,python3 --parallel
+else
+	dh $@ --with autoreconf,python3 $(BOOTSTRAP_DH_FLAGS)
+endif
